new component for Sneakers route
AlexFlorinBucur/sneakerhub-project pull request #6
Opened 2023-08-02 17:32 UTC by AlexFlorinBucur

adding a new component to see sneakers by active filters.

2023-08-02 20:17 UTC, malinmilea requested changes

2023-08-02 20:17 UTC, malinmilea commented on src/Routes/Sneakers/Sneakers.jsx
> +  console.log(activeFilters);
please remove all logs, it might create confusion to users

2023-08-02 20:17 UTC, malinmilea commented on src/Routes/Sneakers/Sneakers.jsx
> +            }
good job, the descriptions are helpful for the devs to understand the code

2023-08-02 20:17 UTC, malinmilea commented on src/Routes/Sneakers/Sneakers.jsx
>        setError(err.message);
please avoid usage of the messages from the server, those are useful only for the devs, but a 404 message is not something descriptive for the user

2023-08-02 20:17 UTC, malinmilea commented on src/Routes/Sneakers/Sneakers.jsx
> +      navigate(``);
''

2023-08-02 20:17 UTC, malinmilea commented on src/components/Sneaker/SneakerFilter.jsx
> +  // console.log(location.search);
rmv

2023-08-02 20:17 UTC, malinmilea commented on src/components/Sneaker/SneakerFilterActive.jsx
> +              </li>
please create a separated component

2023-08-02 20:17 UTC, malinmilea commented on src/components/Sneaker/SneakerList.jsx
> +                    {`Available: `}
```suggestion
                    {'Available: '}
```

2023-08-02 20:58 UTC, AlexFlorinBucur commented on src/Routes/Sneakers/Sneakers.jsx
>        setError(err.message);
I implemented this above

2023-08-02 21:08 UTC, AlexFlorinBucur commented on src/Routes/Sneakers/Sneakers.jsx
> +            }
I will change that in future

2023-08-03 07:34 UTC, malinmilea approved these changes

2023-08-03 07:34 UTC, merged